# Generated by Django 3.0.1 on 2019-12-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\my-portfolio\\personal_portfolio\\static'),
        ),
    ]
