# Generated by Django 3.0.1 on 2019-12-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191218_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\my-portfolio\\personal_portfolio\\static\\img'),
        ),
    ]
